### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by IgorGanapolsky** [richk/CourseraDemoApp#3]
Hello,
there's currently a UI bug in your application, specifically when hitting the back button from CatalogActivity.
EXPECTED RESULT:
should exit the app
ACTUAL RESULT:
shows a blank activity (MainActivity)

See screenshot
![device-2015-12-21-013159](https://cloud.githubusercontent.com/assets/201209/11924744/ac77cc76-a782-11e5-965a-982d07830b05.png)
:

**Comment by richk** [comment]
Is resolved now, thanks for reporting!
