### ISSUE TITLE
Can not find class DaggerApplicationComponent in CourseraDemoApplication.java

### ISSUE THREAD

**Issue by insomniatt** [richk/CourseraDemoApp#4]
I cant find demo.catalog.coursera.org.courserademoapp.di.DaggerApplicationComponent class.

**Comment by ewoks** [comment]
try to clean and rebuild. Dagger2 will auto generate this class for you and you can find it in build folder.

**Comment by maks-novikov** [comment]
same problem here , clean , sync not helping
